In [24]:
import numpy as np

In [ ]:
x = np.arange(1, 9).reshape(2, 4)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
y = np.arange(9, 17).reshape(2, 4)
y

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
x + y

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
y - x

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [ ]:
x * y

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [ ]:
y / x

array([[9.        , 5.        , 3.66666667, 3.        ],
       [2.6       , 2.33333333, 2.14285714, 2.        ]])

In [ ]:
x**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [ ]:
y**(1/2)

array([[3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [ ]:
x**(1/3)

array([[1.        , 1.25992105, 1.44224957, 1.58740105],
       [1.70997595, 1.81712059, 1.91293118, 2.        ]])

In [ ]:
arr = np.random.randn(5, 4)
arr

array([[-1.02548411, -0.30449412, -0.73461566, -0.18853514],
       [-2.51752653, -0.30917548,  2.65961865, -2.01878319],
       [-1.78194483, -1.80507703,  0.01726981,  1.05519493],
       [ 1.74420908,  0.30751988,  0.73760384,  0.49230511],
       [ 0.78150599, -0.42730079, -1.34692518,  0.52286444]])

In [ ]:
np.sum(arr) # sum() function

-4.141770342129021

In [ ]:
np.sum(arr, axis=0)

array([-2.7992404 , -2.53852754,  1.33295145, -0.13695385])

In [ ]:
np.sum(arr, axis=1)

array([-2.25312904, -2.18586655, -2.51455712,  3.28163791, -0.46985554])

In [ ]:
np.mean(arr) # mean() function

-0.20708851710645107

In [ ]:
np.mean(arr, axis=0)

array([-0.55984808, -0.50770551,  0.26659029, -0.02739077])

In [ ]:
np.mean(arr, axis=1)

array([-0.56328226, -0.54646664, -0.62863928,  0.82040948, -0.11746389])

In [ ]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [23]:
np.cumsum(arr1)

array([ 0,  1,  3,  6, 10, 15])

In [25]:
n = np.arange(1, 7).reshape(2, 3)
n

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
m = np.arange(8, 14).reshape(3, 2)
m

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [30]:
np.dot(n, m) # dot function = x * y

array([[ 64,  70],
       [154, 169]])

In [32]:
np.dot(m, n) # dot function = y * x

array([[ 44,  61,  78],
       [ 54,  75,  96],
       [ 64,  89, 114]])

In [33]:
# Liner Algebra
from numpy.linalg import inv