In [ ]:
import numpy as np

In [ ]:
names = np.array(['Nodir', 'Komil', 'Sardor', 'Anvar', 'Sobir', 'Botir', 'Bahrom'])
print(names)

['Nodir' 'Komil' 'Sardor' 'Anvar' 'Sobir' 'Botir' 'Bahrom']


In [ ]:
data = np.random.randn(7, 4)
data

array([[-0.60456374,  0.00244073, -1.07414803, -1.08329912],
       [-0.34284298, -0.78669589,  0.07455309,  0.97365248],
       [ 1.62423291,  0.13846618,  0.4744792 ,  0.68008869],
       [ 0.50963345,  0.26611907,  0.68102358, -1.05589617],
       [-0.25222711,  1.31974444, -1.77449862, -0.92083721],
       [-0.79973412,  1.98297554, -0.14560717,  0.35359751],
       [-1.45297701, -0.23923112,  1.24448079, -1.22378742]])

In [ ]:
data[names == 'Komil']

array([[-0.34284298, -0.78669589,  0.07455309,  0.97365248]])

In [ ]:
data[names == 'Anvar', 2:]

array([[ 0.68102358, -1.05589617]])

In [ ]:
data[data<0] = 0
data

array([[0.        , 0.00244073, 0.        , 0.        ],
       [0.        , 0.        , 0.07455309, 0.97365248],
       [1.62423291, 0.13846618, 0.4744792 , 0.68008869],
       [0.50963345, 0.26611907, 0.68102358, 0.        ],
       [0.        , 1.31974444, 0.        , 0.        ],
       [0.        , 1.98297554, 0.        , 0.35359751],
       [0.        , 0.        , 1.24448079, 0.        ]])

In [ ]:
mask = (names == 'Nodir') | (names == 'Komil')
data[mask]

array([[0.        , 0.00244073, 0.        , 0.        ],
       [0.        , 0.        , 0.07455309, 0.97365248]])