In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr1[1]

2

In [4]:
sliced_arr1 = arr1[2:5].copy()
sliced_arr1

array([3, 4])

In [5]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2d[1, 3]

8

In [8]:
sl_arr2d = arr2d[1, 2:4]
sl_arr2d

array([7, 8])

In [9]:
arr3d = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8]],

                  [[9, 10, 11, 12],
                   [13, 14, 15, 16]],

                  [[17, 18, 19, 20],
                   [21, 22, 23, 24]]])
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [11]:
arr3d[2][0, 2]

19

In [14]:
sl_arr3d = arr3d[1][0, 0:4]
sl_arr3d

array([ 9, 10, 11, 12])