In [1]:
import numpy as np

In [2]:
xarr = np.arange(1.1, 1.6, 0.1)
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [3]:
yarr = np.arange(2.1, 2.6, 0.1)
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [4]:
cond = np.array([True, False, True, True, False])

In [5]:
# where logical set function 1-exercise
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
arr = np.random.randn(3, 4)
arr

array([[-0.63465959,  0.19206381, -0.47630744,  0.3402144 ],
       [ 0.16059001, -0.33499891, -2.12697707, -0.45547005],
       [ 0.20322087, -0.04329922,  0.1749186 ,  0.19030995]])

In [7]:
results = np.where(arr>0, 1, -2)
results

array([[-2,  1, -2,  1],
       [ 1, -2, -2, -2],
       [ 1, -2,  1,  1]])