In [1]:
import numpy as np

In [ ]:
data = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr = np.array(data)

In [ ]:
data

[1, 2, 3, 4]

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.ndim #quantity of massives

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
zero = np.zeros((3, 4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
one = np.ones((3, 4))
zero

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr2 = np.arange(0, 101, 2)
arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
arr2.size

51

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [ ]:
arr1 = np.array([1.8, 2.4, 8.6, 7.8])
arr1.dtype

dtype('float64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
int_arr = arr1.astype(np.int64)
int_arr

array([1, 2, 8, 7])

In [2]:
my_list = list(range(100000)) # python list 0~99999 -->Normal
my_array = np.array(range(100000)) # numpy array(massiv) 0~99999 --> Vektorlashgan

In [3]:
%time for _ in range(10): [x*2 for x in my_list] # Normal

CPU times: user 63.1 ms, sys: 16 ms, total: 79.1 ms
Wall time: 79 ms


In [5]:
%time for _ in range(10): my_array*2 # Vektorlashgan

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.38 ms
