In [1]:
import numpy as np

In [2]:
arr = np.random.randn(2, 4)
arr

array([[-0.88983488, -0.03993112,  1.78578522, -0.30069065],
       [-0.13827377, -1.42564456,  1.12956277, -1.0222204 ]])

In [3]:
np.sort(arr) # simple sorting

array([[-0.88983488, -0.30069065, -0.03993112,  1.78578522],
       [-1.42564456, -1.0222204 , -0.13827377,  1.12956277]])

In [4]:
np.sort(arr, axis=0) # column sorting

array([[-0.88983488, -1.42564456,  1.12956277, -1.0222204 ],
       [-0.13827377, -0.03993112,  1.78578522, -0.30069065]])

In [5]:
np.sort(arr, axis=1) # row sorting

array([[-0.88983488, -0.30069065, -0.03993112,  1.78578522],
       [-1.42564456, -1.0222204 , -0.13827377,  1.12956277]])