In [1]:
import numpy as np

In [7]:
A = np.array(range(6)).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.T # Transpose massive AT

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
np.dot(A, A.T) #AAT

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])