In [1]:
import numpy as np

In [ ]:
# UNARY FUNCTIONS

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr) # sqrt function

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.square(arr) # square function

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
np.exp(arr) # exp function

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
np.log2(arr[1:]) # log function

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [8]:
arr1 = np.random.randn(6)
arr1

array([-0.11708783,  1.50864556, -0.61351843,  0.2531269 , -0.97633177,
       -1.06426632])

In [9]:
qoldiq, butun = np.modf(arr1) # modf function

In [10]:
print(qoldiq)
print(butun)

[-0.11708783  0.50864556 -0.61351843  0.2531269  -0.97633177 -0.06426632]
[-0.  1. -0.  0. -0. -1.]


In [11]:
np.sign(arr1) # sign function

array([-1.,  1., -1.,  1., -1., -1.])

In [12]:
arr1[0] = np.NaN
arr1

array([        nan,  1.50864556, -0.61351843,  0.2531269 , -0.97633177,
       -1.06426632])

In [13]:
np.isnan(arr1) # isnan function

array([ True, False, False, False, False, False])

In [14]:
# BINARY FUNCTIONS

In [15]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [16]:
arr2

array([-0.08159071,  0.18008696, -0.12423039, -1.24243072,  0.29322292,
        1.71064663])

In [17]:
arr3

array([-1.62775868,  0.95203959,  1.03352171,  1.30119817, -0.63525234,
       -0.26067254])

In [18]:
np.add(arr2, arr3) # add function

array([-1.70934939,  1.13212655,  0.90929131,  0.05876745, -0.34202942,
        1.44997409])

In [19]:
np.multiply(arr2, arr3) # multiply function

array([ 0.13280999,  0.17144991, -0.12839481, -1.61664857, -0.18627055,
       -0.4459186 ])

In [20]:
np.maximum(arr2, arr3) # maximum function

array([-0.08159071,  0.95203959,  1.03352171,  1.30119817,  0.29322292,
        1.71064663])