In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('data', arr)

In [4]:
np.load('data.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.savez('arrays', a=arr, b=arr2)

In [10]:
arrays = np.load('arrays.npz')

In [12]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])